export const apiKey = '1ede0fc291ba41a699c81255260801';

export const weatherImages ={ 
    'Partly Cloudy ' : require('../assets/partly-cloudy.png'),
    'Moderate rain' : require('../assets/rainy-day.png'),
    'Patchy rain possible' : require('../assets/rainy-day.png'),
    'Patchy rain nearby' : require('../assets/rainy-day.png'),
    'Sunny' : require('../assets/sun.png'),
    'Mist' : require('../assets/mist.png'),
    'Clear' : require('../assets/sun.png'),
    'Clear ' : require('../assets/sun.png'),
    'Overcast ' : require('../assets/cloudy.png'),
    'Cloudy' : require('../assets/cloudy.png'),
    'Light snow showers' : require('../assets/snowflake.png'),
    'Light sleet' : require('../assets/snowflake.png'),
    'Freezing fog' : require('../assets/snowflake.png'),
    'Blowing snow' : require('../assets/snowflake.png'),
    'Moderate snow' : require('../assets/snowflake.png'),
    'Moderate or heavy snow showers' : require('../assets/snowflake.png'),
    'Light snow' : require('../assets/snowflake.png'),
    'Light rain' : require('../assets/rainy-day.png'),
    'Light freezing rain' : require('../assets/rainy-day.png'),
    'Moderate rain at times' : require('../assets/rainy-day.png'),
    'Heavy rain' : require('../assets/thunder-cloud.png'),
    'Heavy rain at times' : require('../assets/thunder-cloud.png'),
    'Moderate or heavy freezing rain' : require('../assets/thunder-cloud.png'),
    'Moderate or heavy rain shower' : require('../assets/thunder-cloud.png'),
    'Moderate or heavy rain with thunder' : require('../assets/thunder-cloud.png'),
    'other' : require('../assets/partly-cloudy.png'),
}